---

#Reload systemctl to pick up flannel network config
- name: Reload systemctl daemon
  command: /usr/bin/systemctl daemon-reload

#Restart services
- name: Restart flanneld
  service: name=flanneld state=restarted

- name: Restart kubelet
  service: name=kubelet state=restarted

- name: Restart kube-proxy
  service: name=kube-proxy state=restarted

#Remove Certificate Authority files when done generating server certificates
- name: Cleanup CA Files
  file: dest='{{ k8s_node_cert_path }}/{{ item }}'
  with_items:
    - "{{ k8s_apiserver_ca_key_filename }}"
